virtual_stocks/webapp/main/routes.py
from flask import   (render_template,
                    url_for, 
                    flash, 
                    redirect, 
                    request , 
                    abort,
                    Blueprint)

from webapp.main.forms import SearchForm
from webapp.main.utils import search_key


main = Blueprint('main',__name__)

@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def home():
    form = SearchForm()
    if form.validate_on_submit():
        return redirect((url_for('main.search_results', query=form.search.data)))
    return render_template('home.html', form=form)#, posts=posts)

@main.route('/search_results/<query>')
def search_results(query):
  results = search_key(query)
  return render_template('search_results.html', results=results)

@main.route("/about")
def about():
    return render_template('about.html', title ='About')

virtual_stocks/webapp/users/routes.py
from flask import   (render_template,
                    url_for, 
                    flash, 
                    redirect, 
                    request ,                     
                    abort,
                    Blueprint)
from flask_login import (login_user, 
                        current_user, 
                        logout_user, 
                        login_required)
from webapp import db, bcrypt
from webapp.models import User, User_funds, User_stock
from webapp.users.forms import (RegistrationForm, 
                            LoginForm,
                            UpdateAccountForm,
                            BuyForm,
                            AddFundsForm,
                            RequestResetForm,
                            ResetPasswordForm,                            
                            SellForm )
from webapp.main.utils import search_key
from sqlalchemy import func
from webapp.users.utils import send_reset_email

users = Blueprint('users',__name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        user_funds = User_funds(available_funds='10000',user_id=user.id)
        db.session.add(user_funds)
        db.session.commit()
        flash('Your account has been created! Please login to continue.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title ='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessfull. Please check email and password', 'danger')

    return render_template('login.html', title ='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.','success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Please login to continue.', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data =current_user.email
    return render_template('account.html', title ='Account', form=form )

@users.route("/consolidated_history", methods=['GET', 'POST'])
@login_required
def consolidated_history():
    if request.method == 'GET':
        user_fund = User_funds.query.filter_by(user_id=current_user.id).first_or_404()
        user_stock_total_list = db.session.query(User_stock.stock_name,
                                            User_stock.stock_key,
                                            User_stock.stock_price,
                                            func.sum(User_stock.share).label('shares'),
                                            func.sum(User_stock.total_share_price).label('total'))\
                                            .filter_by(user_id=user_fund.user_id)\
                                            .group_by(User_stock.stock_key)\
                                            .order_by(User_stock.stock_name)\
                                            .all()
        if user_fund.author2 != current_user:
            abort(403)
    return render_template('consolidated_history.html', 
                            title ='Consolidated History', 
                            avl_funds= user_fund.available_funds,
                            user_stock_total_list=user_stock_total_list)

@users.route("/buy", methods=['GET', 'POST'])
@login_required
def buy():
    user = User.query.filter_by(id=current_user.id).first_or_404()
    user_fund = User_funds.query.filter_by(id=current_user.id).first_or_404()
    if user_fund.available_funds <= 0:
        flash('Your balance is less than or equal to zero', 'danger')
        return redirect(url_for('users.add_funds'))
    form = BuyForm()
    # if user.id != current_user:
    #     abort(403)
    if form.validate_on_submit():
        results=search_key(form.symbol.data)
        if results == None:
            flash('Invalid Keyword!', 'danger')
            return redirect(url_for('users.buy',user_id=user.id))
        # print(results['price'])
        total_stock_price = results['price'] * int(form.share.data)
        if total_stock_price > user_fund.available_funds:
            flash("Your don't have that much balance", 'danger')
            return redirect(url_for('users.buy'))
        user_stock = User_stock(stock_name=str(results['name']),
                                share=form.share.data,
                                stock_key=form.symbol.data,
                                stock_price=results['price'],
                                total_share_price=total_stock_price,
                                user_id=user.id)
        db.session.add(user_stock)
        db.session.commit()
        
        db.session.query(User_funds).filter_by(id=user.id).update({User_funds.available_funds: User_funds.available_funds - total_stock_price})
        db.session.commit()
        flash('Your bought a share!', 'success')
        return redirect(url_for('users.consolidated_history'))
    
    return render_template('buy.html', title ='Buy', form=form)



@users.route("/sell", methods=['GET', 'POST'])
@login_required
def sell():
    user = User.query.filter_by(id=current_user.id).first_or_404()
    form=SellForm()
    # if user.id != current_user:
    #     abort(403)
    stock_counts = db.session.query(func.sum(User_stock.share)\
                                .label('share_total'),
                                User_stock.stock_key)\
                                .filter(User_stock.user_id==user.id)\
                                .group_by(User_stock.stock_key)\
                                .all()
    removed_stocks=[stock_count[1] for stock_count in stock_counts if stock_count['share_total'] == 0]
    
    stock_names = db.session.query(func.distinct(User_stock.stock_key)\
                                .label('distinct_stock_key'))\
                                .filter(User_stock.user_id==user.id)\
                                .all()
    choices=["".join(stock_name) for stock_name in stock_names]
    choices= [act_chc for act_chc in choices if act_chc not in removed_stocks]

    if len(choices) == 0 :
        flash('Buy share first to sell', 'danger')
        return redirect(url_for('users.buy'))
    # stock_names = db.session.query(func.sum(User_stock.share),User_stock.stock_key).filter_by(user_id=user.id).all()
    
    choices.append("Select")
    form.symbol.choices= choices[::-1]
    form.symbol.default=0
    
    if form.validate_on_submit():
        stock_price = search_key(form.symbol.data)
        form.share.data = int(form.share.data) * (-1)
        total_stock_price = stock_price['price'] * form.share.data
        user_stock = User_stock(stock_name=str(stock_price['name']),
                                share=form.share.data,
                                stock_key=form.symbol.data,
                                stock_price=stock_price['price'],
                                total_share_price=total_stock_price,
                                user_id=user.id)
        db.session.add(user_stock)
        db.session.commit()
        
        db.session.query(User_funds).filter_by(id=user.id).update({User_funds.available_funds: User_funds.available_funds - total_stock_price})
        db.session.commit()
        flash('Your just sold the share!', 'success')
        return redirect(url_for('users.consolidated_history'))
    return render_template('buy.html', title ='Buy', form=form)



@users.route("/history", methods=['GET', 'POST'])

virtual_stocks/webapp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <legend>About Us</legend>
        <p>This is a dummy site created as a personal project for working with dummy Virtual Stocks. 
            You can Buy, sell as well as see your transaction History, add funds as will search for the quites of the stocks you want to buy.
            Also Please Note that the data here is being fetched directly from IEX Cloud and is real time data for the stocks.
        </p>
    </div>
{% endblock content %}

virtual_stocks/webapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <div class="media">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

virtual_stocks/webapp/templates/add_funds.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Funds</legend>
                <div class="form-group">
                    {{ form.funds.label(class="form-control-label") }}

                    {% if form.funds.errors %}
                        {{ form.funds(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.funds.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.funds(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

virtual_stocks/webapp/templates/buy.html
{% extends "layout.html" %}
{% block content %}
    {{ current_user.username }}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Buy Stocks</legend>
                <div class="form-group">
                    {{ form.symbol.label(class="form-control-label") }}

                    {% if form.symbol.errors %}
                        {{ form.symbol(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.symbol.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.symbol(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.share.label(class="form-control-label") }}
                    {% if form.share.errors %}
                        {{ form.share(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.share.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.share(class="form-control form-control-lg") }}
                    {% endif %}                
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

virtual_stocks/webapp/templates/consolidated_history.html
{% extends "layout.html" %}
{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Symbol</th>
        <th scope="col">Price</th>
        <th scope="col">Shares</th>
        <th scope="col">Total</th>
      </tr>
    </thead>

    <tbody>
      
        
        {% for user_stock_total in user_stock_total_list %}
        <tr style="font-weight:bold">
          <td>{{ user_stock_total.stock_name }}</td>
          <td>{{ user_stock_total.stock_key }}</td>
          <td>NA</td>
          <td>{{ user_stock_total.shares }}</td>
          <td>${{ user_stock_total.total }}</td>
        </tr> 
        {% endfor %}

      

      <tfoot>
        

         
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td class="border-0 fw-bold text-end" >CASH</td>
            <td class="border-0 w-bold text-end">${{ avl_funds }}</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td class="border-0 fw-bold text-end" >TOTAL</td>
            <td class="border-0 w-bold text-end">${{ avl_funds }}</td>
          </tr>
      </tfoot>
</table>
{% endblock content %}

virtual_stocks/webapp/templates/history.html
{% extends "layout.html" %}
{% block content %}
<legend class="h1 mb-4 text-center">Your Transactions</legend>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Symbol</th>
        <th scope="col">Price</th>
        <th scope="col">Shares</th>
        <th scope="col">Total</th>
      </tr>
    </thead>

    <tbody>
        {% for user_stock in user_stock_list %}
        <tr>
          <td>{{ user_stock.stock_name }}</td>
          <td>{{ user_stock.stock_key }}</td>
          <td>${{ user_stock.stock_price }}</td>
          <td>{{ user_stock.share }}</td>
          <td>${{ user_stock.total_share_price }}</td>
        </tr>
        {% endfor %}
        {% for user_stock_total in user_stock_total_list %}
        <tr style="font-weight:bold">
          <td>{{ user_stock_total.stock_name }}</td>
          <td>{{ user_stock_total.stock_key }}</td>
          <td>NA</td>
          <td>{{ user_stock_total.shares }}</td>
          <td>${{ user_stock_total.total }}</td>
        </tr> 
        {% endfor %}
    </tbody>    

      <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td class="border-0 fw-bold text-end" >CASH</td>
            <td class="border-0 w-bold text-end">${{ avl_funds }}</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td class="border-0 fw-bold text-end" >TOTAL</td>
            <td class="border-0 w-bold text-end">${{ avl_funds }}</td>
          </tr>
      </tfoot>
</table>
{% endblock content %}

virtual_stocks/webapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
        <form class="card card-sm" method="POST">
            <div class="card-body row no-gutters align-items-center">
                <div class="col-auto">
                    <i class="fas fa-search h4 text-body"></i>
                </div>
                <!--end of col-->
                <div class="col">
                    {{ form.search(class="form-control form-control-lg form-control-borderless" ,type="search", placeholder="Search stocks with keywords") }} 
                    
                </div>
                <!--end of col-->
                <div class="col-auto">
                    {{ form.submit }}
                    {{ form.csrf_token }}
                </div>
                <!--end of col-->
            </div>
        </form>
    </div>
    <!--end of col-->
</div>
</div>
{% endblock content %}

virtual_stocks/webapp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


      {% if title %}
          <title>CS50 webapp 2021 - {{ title }}</title>
      {% else %}
          <title>CS50 webapp 2021</title>
      {% endif %}
  </head>

  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-md navbar-light bg-light border">
      <!-- <a class="navbar-brand" href="/"><span class="blue">C</span><span class="red">$</span><span class="yellow">5</span><span class="green">0</span> <span class="red">Finance</span></a> -->
      <a class="navbar-brand" href="{{ url_for('main.home') }}">
        <span class="blue">__</span>
        <span class="red">Stock</span>
        <span class="yellow">Exchange</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbar">
        
        {% if current_user.is_authenticated %}
        <ul class="navbar-nav mb-auto mt-2">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.home') }}">Quote  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.buy') }}">Buy  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.sell') }}">Sell  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.history') }}">History  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.consolidated_history') }}">Consolidated History  <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto mt-2">
          {% if request.endpoint in  ['users.buy','users.account','users.history','users.consolidated_history']  %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.add_funds') }}">Add Funds  <span class="sr-only">(current)</span></a>
          </li>
          {% endif %} 
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.account') }}">{{ current_user.username.capitalize() }}  <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout  <span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <ul class="navbar-nav ml-auto mt-2">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.register') }}">Register <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main role="body" class="container py-5" style="margin-top: 5%;">
      <div class="row" >
        <div class="col-lg-10 mx-auto">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <footer class="mt-auto small text-center text-muted">
      <div >
        {% if request.endpoint != 'main.about'  %}
        <a class="mb-4" href="{{ url_for('main.about') }}" >About Us </a>
        {% else %}
        <a class="mb-4" href="https://www.linkedin.com/in/debarghya-bhattacharya">Developed by debriv</a>
        {% endif %}    
      </div>
      
  </footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

virtual_stocks/webapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}               
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small  class="text-muted ml-2 ">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div> 
    </form>
</div>
<div class="form-group">
    <small class="text-muted">
        Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

virtual_stocks/webapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}                </div>                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}